package ar.com.racasoft.principal;

import ar.org.centro8smata.curso.java.conector.Table;
import static ar.org.centro8smata.curso.java.conector.Table.select;
import ar.org.centro8smata.curso.java.util.Box;
import ar.org.centro8smata.curso.java.util.Log;
import ar.org.centro8smata.curso.java.util.SwingTable;
//Importo por las dudas
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;

/**
 * Proyecto PrograMandra versión posta / Noviembre 2016
 * @author RACA SOFT 
 */
public class AlumnosManagment extends javax.swing.JFrame {

    /**
     * Creates new form AlumnosManagment
     */
    public AlumnosManagment() { // al arrancar el programa, hace esto
        initComponents();
        cargarTablaAlumnos();
        cargarTablaContactos();
        cargarTablaFinanzas();
        cargarItemsFinanzas();
    }
    
    public void cargarTablaAlumnos() {
        // Cargar tblAlumnos (carga en la tabla los valores de la base de datos.)
        SwingTable.cargar(Table.select("alumnos"), tblAlumnos);    
    }//End cargar()
        
    public void cargarTablaContactos(){
        // Cargar tblContactos (carga en la tabla los valores de la base de datos.)
        SwingTable.cargar(Table.select("contactos"), tblContactos);    
    }
    
    public void cargarTablaFinanzas(){
        // Cargar tblFinanzas (carga en la tabla los valores de la base de datos.)
        SwingTable.cargar(Table.select("finanzas"), tblFinanzas);
        actualizarSaldo();
    }
    
    public void actualizarSaldo() {
        
        // Actualiza el saldo en el txtSaldo
        txtSaldo.setText(Table.selectSum("finanzas", "importe")+""); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnGeneral = new javax.swing.JTabbedPane();
        pnlAlumnos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscaAl = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnEditar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtUltiPago = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnAgregarAl = new javax.swing.JButton();
        btnBackup = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        pnlFinanzas = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCobroConcepto = new javax.swing.JTextField();
        txtGastoMonto = new javax.swing.JTextField();
        btnAgregarCobro = new javax.swing.JButton();
        btnAgregarGasto = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtCobroMonto = new javax.swing.JTextField();
        cmbConGasto = new javax.swing.JComboBox<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFinanzas = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        cmbDia = new javax.swing.JComboBox<String>();
        cmbMes = new javax.swing.JComboBox<String>();
        cmbAno = new javax.swing.JComboBox<String>();
        txtSaldo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnEliminarCampo = new javax.swing.JButton();
        btnSaldoGeneral = new javax.swing.JButton();
        btnSaldoMensual = new javax.swing.JButton();
        btnSaldoSemanal = new javax.swing.JButton();
        btnSaldoPersonalizado = new javax.swing.JButton();
        pnlContactos = new javax.swing.JPanel();
        txtNombre1 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtTelefono1 = new javax.swing.JTextField();
        txtCelular1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        txtWeb = new javax.swing.JTextField();
        btnAgregarCont = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtBuscaCont = new javax.swing.JTextField();
        btnEditar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnBackup1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblContactos = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtObser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RACA Management Académico");
        setResizable(false);

        tpnGeneral.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Buscar alumno:");

        txtBuscaAl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBuscaAl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaAlKeyReleased(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Teléfono:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Celular:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Dirección:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("E-mail:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Último mes pago:");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtCelular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtUltiPago.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAgregarAl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregarAl.setText("Agregar Alumno");
        btnAgregarAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlActionPerformed(evt);
            }
        });

        btnBackup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBackup.setText("Backup");

        tblAlumnos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Teléfono", "Celular", "E-mail", "Dirección", "Último mes pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlumnos.setCellSelectionEnabled(false);
        tblAlumnos.setRowSelectionAllowed(true);
        tblAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlumnosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblAlumnos);
        if (tblAlumnos.getColumnModel().getColumnCount() > 0) {
            tblAlumnos.getColumnModel().getColumn(0).setResizable(false);
            tblAlumnos.getColumnModel().getColumn(1).setResizable(false);
            tblAlumnos.getColumnModel().getColumn(2).setResizable(false);
            tblAlumnos.getColumnModel().getColumn(3).setResizable(false);
            tblAlumnos.getColumnModel().getColumn(4).setResizable(false);
            tblAlumnos.getColumnModel().getColumn(5).setResizable(false);
            tblAlumnos.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout pnlAlumnosLayout = new javax.swing.GroupLayout(pnlAlumnos);
        pnlAlumnos.setLayout(pnlAlumnosLayout);
        pnlAlumnosLayout.setHorizontalGroup(
            pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(pnlAlumnosLayout.createSequentialGroup()
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAlumnosLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUltiPago, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAlumnosLayout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(btnAgregarAl, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlAlumnosLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscaAl, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnEliminar)
                        .addGap(42, 42, 42)
                        .addComponent(btnBackup)))
                .addContainerGap(105, Short.MAX_VALUE))
            .addComponent(jScrollPane4)
        );
        pnlAlumnosLayout.setVerticalGroup(
            pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlumnosLayout.createSequentialGroup()
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAlumnosLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAlumnosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregarAl)))
                .addGap(18, 18, 18)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtUltiPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscaAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnBackup))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        tpnGeneral.addTab("Alumnos", pnlAlumnos);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Cobro (monto):");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Gasto (monto):");

        txtCobroConcepto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGastoMonto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAgregarCobro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregarCobro.setText("Agregar Cobro");
        btnAgregarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCobroActionPerformed(evt);
            }
        });

        btnAgregarGasto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregarGasto.setText("Agregar Gasto");
        btnAgregarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarGastoActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Concepto:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Concepto:");

        txtCobroMonto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCobroMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCobroMontoActionPerformed(evt);
            }
        });

        cmbConGasto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbConGasto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbConGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConGastoActionPerformed(evt);
            }
        });

        tblFinanzas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblFinanzas);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Fecha:");

        cmbDia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiaActionPerformed(evt);
            }
        });

        cmbMes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesActionPerformed(evt);
            }
        });

        cmbAno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAnoActionPerformed(evt);
            }
        });

        txtSaldo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Saldo total del período seleccionado:");

        btnEliminarCampo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminarCampo.setText("Eliminar campo seleccionado");
        btnEliminarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCampoActionPerformed(evt);
            }
        });

        btnSaldoGeneral.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSaldoGeneral.setText("General");
        btnSaldoGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoGeneralActionPerformed(evt);
            }
        });

        btnSaldoMensual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSaldoMensual.setText("Último mes");
        btnSaldoMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoMensualActionPerformed(evt);
            }
        });

        btnSaldoSemanal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSaldoSemanal.setText("Última semana");
        btnSaldoSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoSemanalActionPerformed(evt);
            }
        });

        btnSaldoPersonalizado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSaldoPersonalizado.setText("Personalizado");
        btnSaldoPersonalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoPersonalizadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFinanzasLayout = new javax.swing.GroupLayout(pnlFinanzas);
        pnlFinanzas.setLayout(pnlFinanzasLayout);
        pnlFinanzasLayout.setHorizontalGroup(
            pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinanzasLayout.createSequentialGroup()
                .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFinanzasLayout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlFinanzasLayout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(56, 56, 56)
                                    .addComponent(txtCobroConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlFinanzasLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCobroMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(85, 85, 85)
                            .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel22))
                            .addGap(31, 31, 31)
                            .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGastoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbConGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlFinanzasLayout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlFinanzasLayout.createSequentialGroup()
                                    .addComponent(btnAgregarCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                                    .addComponent(btnAgregarGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlFinanzasLayout.createSequentialGroup()
                                    .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlFinanzasLayout.createSequentialGroup()
                                            .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnSaldoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnSaldoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnSaldoSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnSaldoPersonalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(109, 109, 109)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlFinanzasLayout.createSequentialGroup()
                                            .addComponent(jLabel24)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(pnlFinanzasLayout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel23)
                        .addGap(52, 52, 52)
                        .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(cmbAno, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFinanzasLayout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(btnEliminarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFinanzasLayout.setVerticalGroup(
            pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFinanzasLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(txtGastoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCobroMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(txtCobroConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbConGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCobro)
                    .addComponent(btnAgregarGasto))
                .addGap(27, 27, 27)
                .addComponent(btnEliminarCampo)
                .addGap(26, 26, 26)
                .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFinanzasLayout.createSequentialGroup()
                        .addComponent(btnSaldoGeneral)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaldoMensual)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaldoSemanal))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaldoPersonalizado)
                .addGap(49, 49, 49)
                .addGroup(pnlFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(632, 632, 632))
        );

        tpnGeneral.addTab("Finanzas personales", pnlFinanzas);

        txtNombre1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtApellido1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTelefono1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtCelular1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtEmail1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtWeb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAgregarCont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregarCont.setText("Agregar Contacto");
        btnAgregarCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarContActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Apellido:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Teléfono:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Celular:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("E-mail:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Sitio WEB:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Buscar Contacto:");

        txtBuscaCont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBuscaCont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaContKeyReleased(evt);
            }
        });

        btnEditar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditar1.setText("Editar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnBackup1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBackup1.setText("Backup");

        tblContactos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Teléfono", "Celular", "E-mail", "Sitio Web", "Observaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblContactos);
        if (tblContactos.getColumnModel().getColumnCount() > 0) {
            tblContactos.getColumnModel().getColumn(0).setResizable(false);
            tblContactos.getColumnModel().getColumn(1).setResizable(false);
            tblContactos.getColumnModel().getColumn(2).setResizable(false);
            tblContactos.getColumnModel().getColumn(3).setResizable(false);
            tblContactos.getColumnModel().getColumn(4).setResizable(false);
            tblContactos.getColumnModel().getColumn(5).setResizable(false);
            tblContactos.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Observaciones:");

        txtObser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtObser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContactosLayout = new javax.swing.GroupLayout(pnlContactos);
        pnlContactos.setLayout(pnlContactosLayout);
        pnlContactosLayout.setHorizontalGroup(
            pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(pnlContactosLayout.createSequentialGroup()
                .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactosLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel16))
                        .addGap(59, 59, 59)
                        .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObser, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlContactosLayout.createSequentialGroup()
                                .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(btnAgregarCont, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlContactosLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscaCont, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnEliminar1)
                        .addGap(42, 42, 42)
                        .addComponent(btnBackup1)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        pnlContactosLayout.setVerticalGroup(
            pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContactosLayout.createSequentialGroup()
                .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactosLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlContactosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregarCont)))
                .addGap(18, 18, 18)
                .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtObser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtBuscaCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar1)
                    .addComponent(btnEditar1)
                    .addComponent(btnBackup1))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpnGeneral.addTab("Contactos estratégicos", pnlContactos);

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel1.setText("RACA Management Académico");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("RACA SOFT ® 2016");

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem1.setText("Realizar Back up");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Varios");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem3.setText("Acerca de!");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpnGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tpnGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarItemsFinanzas() { // Carga todos los combobox de finanzas
        
        // Cargar los items de los coneptos a los gastos
        cmbConGasto.removeAllItems();
        cmbConGasto.addItem("Impuestos");
        cmbConGasto.addItem("Servicios");
        cmbConGasto.addItem("Sueldos/Honorarios");
        cmbConGasto.addItem("Comida/Bebida");
        cmbConGasto.addItem("Movilidad");
        cmbConGasto.addItem("Novia/putas");
        cmbConGasto.addItem("Otros");
        
        // Cargar los items de los días
        cmbDia.removeAllItems();
        cmbDia.addItem("1");
        cmbDia.addItem("2");
        cmbDia.addItem("3");
        cmbDia.addItem("4");
        cmbDia.addItem("5");
        cmbDia.addItem("6");
        cmbDia.addItem("7");
        cmbDia.addItem("8");
        cmbDia.addItem("9");
        cmbDia.addItem("10");
        cmbDia.addItem("11");
        cmbDia.addItem("12");
        cmbDia.addItem("13");
        cmbDia.addItem("14");
        cmbDia.addItem("15");
        cmbDia.addItem("16");
        cmbDia.addItem("17");
        cmbDia.addItem("18");
        cmbDia.addItem("19");
        cmbDia.addItem("20");
        cmbDia.addItem("21");
        cmbDia.addItem("22");
        cmbDia.addItem("23");
        cmbDia.addItem("24");
        cmbDia.addItem("25");
        cmbDia.addItem("26");
        cmbDia.addItem("27");
        cmbDia.addItem("28");
        cmbDia.addItem("29");
        cmbDia.addItem("30");
        cmbDia.addItem("31");
        
        // Cargar los items de los meses
        cmbMes.removeAllItems();
        cmbMes.addItem("Enero");
        cmbMes.addItem("Febrero");
        cmbMes.addItem("Marzo");
        cmbMes.addItem("Abril");
        cmbMes.addItem("Mayo");
        cmbMes.addItem("Junio");
        cmbMes.addItem("Julio");
        cmbMes.addItem("Agosto");
        cmbMes.addItem("Septiembre");
        cmbMes.addItem("Octubre");
        cmbMes.addItem("Noviembre");
        cmbMes.addItem("Diciembre");
        
        // Cargar los items de los años
        cmbAno.removeAllItems();
        cmbAno.addItem("2010");
        cmbAno.addItem("2011");
        cmbAno.addItem("2012");
        cmbAno.addItem("2013");
        cmbAno.addItem("2014");
        cmbAno.addItem("2015");
        cmbAno.addItem("2016");
        cmbAno.addItem("2017");
        cmbAno.addItem("2018");
        cmbAno.addItem("2019");
        cmbAno.addItem("2020");
        cmbAno.addItem("2021");    
    } // End cargarItemsFinanzas()
    
    
    private void txtObserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObserActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // Evento Eliminar Contactos (borra el contacto seleccionado de la tabla)
        String filtro="id="+tblContactos.getValueAt(tblContactos.getSelectedRow(), 0);
        if(Box.question(this,"¿Está seguro que lo quiere borrar?")) {
            Table.delete("contactos", filtro);
        }
        cargarTablaContactos();
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // Evento editar contactos estratégicos
        String idContacto;
        if(tblContactos.getSelectedRow()!=-1) {
            idContacto=tblContactos.getValueAt(tblContactos.getSelectedRow(), 0)+"";  
            new ModificarContactos(idContacto,this).setVisible(true);             
        }
        else {
            Box.msg("Flaco, tenés que seleccionar un chaboncito");
        }
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void txtBuscaContKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaContKeyReleased
        // Evento Buscar Contacto
        String filtro="apellido like '%"+txtBuscaCont.getText()+"%' or nombre like '%"+txtBuscaCont.getText()+"%'";
        SwingTable.cargar(Table.select("contactos", filtro), tblContactos);
    }//GEN-LAST:event_txtBuscaContKeyReleased

    private void btnAgregarContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarContActionPerformed
        // Evento agregarContacto
        String fields="Nombre,Apellido,Teléfono,Celular,Email,SitioWeb,Observaciones";
        String values="'"+txtNombre1.getText()+"','"+txtApellido1.getText()+"',"+
        txtTelefono1.getText()+","+txtCelular1.getText()+",'"+txtEmail1.getText()
        +"','"+txtWeb.getText()+"','"+txtObser.getText()+"'";
        int x=Table.insert("contactos", fields, values);
        System.out.println("Han sido insertados "+x+" registros");
        Box.msg("Han sido insertados "+x+" registros");
        cargarTablaContactos();
    }//GEN-LAST:event_btnAgregarContActionPerformed

    private void btnAgregarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarGastoActionPerformed
        // Evento Agregar Gasto
        String fields="importe,concepto,fecha"; // se definen los campos de la tabla
        float importe=Float.parseFloat(txtGastoMonto.getText());
        importe*=-1;
        String concepto=cmbConGasto.getSelectedItem()+"";
        String mes = null; // Se pasa el mes a número para que SQL lo reconozca
        if(cmbMes.getSelectedItem()=="Enero") mes="01";
        else if(cmbMes.getSelectedItem()=="Febrero") mes="02";
        else if(cmbMes.getSelectedItem()=="Marzo") mes="03";
        else if(cmbMes.getSelectedItem()=="Abril") mes="04";
        else if(cmbMes.getSelectedItem()=="Mayo") mes="05";
        else if(cmbMes.getSelectedItem()=="Junio") mes="06";
        else if(cmbMes.getSelectedItem()=="Julio") mes="07";
        else if(cmbMes.getSelectedItem()=="Agosto") mes="08";
        else if(cmbMes.getSelectedItem()=="Septiembre") mes="09";
        else if(cmbMes.getSelectedItem()=="Octubre") mes="10";
        else if(cmbMes.getSelectedItem()=="Noviembre") mes="11";
        else if(cmbMes.getSelectedItem()=="Diciembre") mes="12";
        String fecha=cmbAno.getSelectedItem()+"/"+mes+"/"+
                cmbDia.getSelectedItem();
        String values=importe+",'"+concepto+"','"+fecha+"'"; //Se arman los values
        int x=Table.insert("finanzas", fields, values);
        System.out.println("Han sido insertados "+x+" registros");
        Box.msg("Han sido insertados "+x+" registros");
        cargarTablaFinanzas();
        actualizarSaldo();
    }//GEN-LAST:event_btnAgregarGastoActionPerformed

    private void btnAgregarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCobroActionPerformed
        // Evento Agregar Cobro
        String fields="importe,concepto,fecha";
        String mes = null;
        if(cmbMes.getSelectedItem()=="Enero") mes="01";
        else if(cmbMes.getSelectedItem()=="Febrero") mes="02";
        else if(cmbMes.getSelectedItem()=="Marzo") mes="03";
        else if(cmbMes.getSelectedItem()=="Abril") mes="04";
        else if(cmbMes.getSelectedItem()=="Mayo") mes="05";
        else if(cmbMes.getSelectedItem()=="Junio") mes="06";
        else if(cmbMes.getSelectedItem()=="Julio") mes="07";
        else if(cmbMes.getSelectedItem()=="Agosto") mes="08";
        else if(cmbMes.getSelectedItem()=="Septiembre") mes="09";
        else if(cmbMes.getSelectedItem()=="Octubre") mes="10";
        else if(cmbMes.getSelectedItem()=="Noviembre") mes="11";
        else if(cmbMes.getSelectedItem()=="Diciembre") mes="12";
        String fecha=cmbAno.getSelectedItem()+"/"+mes+"/"+
                cmbDia.getSelectedItem();
        String values=txtCobroMonto.getText()+",'"+txtCobroConcepto.getText()+"','"+fecha+"'";
        int x=Table.insert("finanzas", fields, values);
        System.out.println("Han sido insertados "+x+" registros");
        Box.msg("Han sido insertados "+x+" registros");
        cargarTablaFinanzas();
        actualizarSaldo();
    }//GEN-LAST:event_btnAgregarCobroActionPerformed

    private void btnAgregarAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlActionPerformed
        // Evento Agregar Alumno
        String fields="nombre,apellido,telefono,celular,email,direccion,ultimoPago";
        String values="'"+txtNombre.getText()+"','"+txtApellido.getText()+"',"+
        txtTelefono.getText()+","+txtCelular.getText()+",'"+txtEmail.getText()
        +"','"+txtDireccion.getText()+"','"+txtUltiPago.getText()+"'";
        int x=Table.insert("alumnos", fields, values);
        System.out.println("Han sido insertados "+x+" registros");
        Box.msg("Han sido insertados "+x+" registros");
        cargarTablaAlumnos();
    }//GEN-LAST:event_btnAgregarAlActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Evento Editar alumno
        String idAlumno;
        if(tblAlumnos.getSelectedRow()!=-1) {
            idAlumno=tblAlumnos.getValueAt(tblAlumnos.getSelectedRow(), 0)+"";  
            new ModificarAlumnos(idAlumno,this).setVisible(true);             
        }
        else {
            Box.msg("Flaco, tenés que seleccionar un alumno");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Evento Eliminar Alumno
        String filtro="id="+tblAlumnos.getValueAt(tblAlumnos.getSelectedRow(), 0);
        if(Box.question(this,"¿Está seguro que lo quiere borrar?")) {
            Table.delete("alumnos", filtro);
        }
        cargarTablaAlumnos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscaAlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaAlKeyReleased
        // Evento BuscaAl (Buscar alumnos)
        String filtro="apellido like '%"+txtBuscaAl.getText()+"%' or nombre like '%"+txtBuscaAl.getText()+"%'";
        SwingTable.cargar(Table.select("alumnos", filtro), tblAlumnos);
    }//GEN-LAST:event_txtBuscaAlKeyReleased

    private void txtCobroMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCobroMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCobroMontoActionPerformed

    private void cmbConGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbConGastoActionPerformed

    private void cmbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDiaActionPerformed

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMesActionPerformed

    private void cmbAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAnoActionPerformed

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    private void btnEliminarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCampoActionPerformed
        // Evento eliminar campo seleccionado de finanzas
        String filtro="id="+tblFinanzas.getValueAt(tblFinanzas.getSelectedRow(), 0);
        if(Box.question(this,"¿Está seguro que lo quiere borrar?")) {
            Table.delete("finanzas", filtro);
        }
        cargarTablaFinanzas();
    }//GEN-LAST:event_btnEliminarCampoActionPerformed

    private void tblAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAlumnosMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Evento Acerca de
        Box.msg(this,"Raca Soft Management Académico.\nRACA SOFT®.");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // Evento Salir
        if(Box.question(this, "¿Estás seguro que te querés ir?")) System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnSaldoGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaldoGeneralActionPerformed

    private void btnSaldoMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoMensualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaldoMensualActionPerformed

    private void btnSaldoSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoSemanalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaldoSemanalActionPerformed

    private void btnSaldoPersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoPersonalizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaldoPersonalizadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnosManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnosManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnosManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnosManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnosManagment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAl;
    private javax.swing.JButton btnAgregarCobro;
    private javax.swing.JButton btnAgregarCont;
    private javax.swing.JButton btnAgregarGasto;
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnBackup1;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminarCampo;
    private javax.swing.JButton btnSaldoGeneral;
    private javax.swing.JButton btnSaldoMensual;
    private javax.swing.JButton btnSaldoPersonalizado;
    private javax.swing.JButton btnSaldoSemanal;
    private javax.swing.JComboBox<String> cmbAno;
    private javax.swing.JComboBox<String> cmbConGasto;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pnlAlumnos;
    private javax.swing.JPanel pnlContactos;
    private javax.swing.JPanel pnlFinanzas;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTable tblContactos;
    private javax.swing.JTable tblFinanzas;
    private javax.swing.JTabbedPane tpnGeneral;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtBuscaAl;
    private javax.swing.JTextField txtBuscaCont;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCelular1;
    private javax.swing.JTextField txtCobroConcepto;
    private javax.swing.JTextField txtCobroMonto;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtGastoMonto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtObser;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtUltiPago;
    private javax.swing.JTextField txtWeb;
    // End of variables declaration//GEN-END:variables
}
